# Generated by Django 6.0.6 on 2026-06-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Dépendance simplifiée vers 0001 !
        ('mentorat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('relation', models.OneToOneField(db_column='relation_id', on_delete=django.db.models.deletion.CASCADE, to='mentorat.relationmentorat')),
            ],
            options={
                'db_table': 'conversation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(db_column='contenu')),
                ('lu', models.BooleanField(db_column='lu', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('expediteur', models.ForeignKey(db_column='expediteur_id', on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
    ]