# Generated by Django 6.0.6 on 2026-06-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['date_envoi']},
        ),
    ]
