# Generated by Django 6.0.6 on 2026-06-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(db_column='auteur_id', on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
                ('publication', models.ForeignKey(db_column='publication_id', on_delete=django.db.models.deletion.CASCADE, to='publications.demande')),
            ],
            options={
                'db_table': 'reponse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelationMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='ACTIVE', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True, db_column='date_debut')),
                ('date_fin', models.DateTimeField(blank=True, db_column='date_fin', null=True)),
                ('commentaire_fin', models.TextField(blank=True, db_column='commentaire_fin', null=True)),
                ('mentor', models.ForeignKey(db_column='mentor_id', on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relations', to='core.utilisateur')),
                ('mentore', models.ForeignKey(db_column='mentore_id', on_delete=django.db.models.deletion.CASCADE, related_name='mentore_relations', to='core.utilisateur')),
                ('reponse', models.OneToOneField(db_column='reponse_id', on_delete=django.db.models.deletion.CASCADE, to='mentorat.reponse')),
            ],
            options={
                'db_table': 'relation_mentorat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelationDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(db_column='domaine_id', on_delete=django.db.models.deletion.CASCADE, to='core.domaine')),
                ('relation', models.ForeignKey(db_column='relation_id', on_delete=django.db.models.deletion.CASCADE, to='mentorat.relationmentorat')),
            ],
            options={
                'db_table': 'relation_domaine',
                'managed': True,
                'unique_together': {('relation', 'domaine')},
            },
        ),
        migrations.CreateModel(
            name='ReponseDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(db_column='domaine_id', on_delete=django.db.models.deletion.CASCADE, to='core.domaine')),
                ('reponse', models.ForeignKey(db_column='reponse_id', on_delete=django.db.models.deletion.CASCADE, to='mentorat.reponse')),
            ],
            options={
                'db_table': 'reponse_domaine',
                'managed': True,
                'unique_together': {('reponse', 'domaine')},
            },
        ),
    ]
