# Generated by Django 6.0.6 on 2026-06-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='besoin',
            unique_together={('utilisateur', 'domaine')},
        ),
        migrations.AlterUniqueTogether(
            name='maitrise',
            unique_together={('utilisateur', 'domaine')},
        ),
    ]
