# Generated by Django 6.0.6 on 2026-06-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(db_column='type_notification', max_length=50)),
                ('contenu', models.TextField(db_column='contenu')),
                ('lu', models.BooleanField(db_column='lu', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('utilisateur', models.ForeignKey(db_column='utilisateur_id', on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
            options={
                'db_table': 'notification',
                'managed': True,
            },
        ),
    ]
