# Generated by Django 6.0.6 on 2026-06-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),  # Dépendance cruciale ajoutée !
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(db_column='auteur_id', on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),  # Champ rajouté !
                ('date_publication', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('type', models.CharField(db_column='type_publication', default='DEMANDE', max_length=20)),
                ('statut', models.CharField(db_column='statut', default='OUVERTE', max_length=20)),
                ('titre', models.CharField(default="Demande d'aide", max_length=255)),
                ('description', models.TextField(default='')),
                ('mode_mentorat', models.CharField(db_column='mode_mentorat', default='EN_LIGNE', max_length=20)),
            ],
            options={
                'db_table': 'publication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemandeDisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.ForeignKey(db_column='publication_id', on_delete=django.db.models.deletion.CASCADE, to='publications.demande')),  # Champ rajouté !
                ('jour_semaine', models.IntegerField(db_column='jour_semaine')),
                ('heure_debut', models.TimeField(db_column='heure_debut', default='08:00:00')),
                ('heure_fin', models.TimeField(db_column='heure_fin', default='18:00:00')),
            ],
            options={
                'db_table': 'disponibilite_publication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemandeDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.ForeignKey(db_column='publication_id', on_delete=django.db.models.deletion.CASCADE, to='publications.demande')),  # Champ rajouté !
                ('domaine', models.ForeignKey(db_column='domaine_id', on_delete=django.db.models.deletion.CASCADE, to='core.domaine')),  # Champ rajouté !
            ],
            options={
                'db_table': 'publication_domaine',
                'managed': True,
            },
        ),
    ]
